spring:
  application:
    name: SuperAgent
  config:
    import: optional:application-local.yml
server:
  port: 8123
  servlet:
    context-path: /api  #???????  ????/api?????  ?????
# springdoc-openapi????????   knife4j
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yuqiqi.superagent.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn
# 自定义Spring ai默认的拦截级别
logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug
